/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Graphics3Ainstances = {
	ipv4: string;
	timestamp: number;
	bundleName: string;
	bundleVersion: string;
	bundleGit?: {
		[k: string]: unknown;
	};
	pathName: string;
	singleInstance: boolean;
	socketId: string;
	open: boolean;
	potentiallyOutOfDate: boolean;
}[];
