/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CueFile = {
	sum?: string;
	base?: string;
	ext?: string;
	name?: string;
	url?: string;
	default?: boolean;
	[k: string]: unknown;
} & CueFile1;
export type CueFile1 = {
	sum?: string;
	base?: string;
	ext?: string;
	name?: string;
	url?: string;
	default?: boolean;
	[k: string]: unknown;
} | null;
export type SoundCues = {
	name: string;
	volume: number;
	channels?: number;
	bundleName?: string;
	defaultVolume?: number | null;
	file: CueFile;
	defaultFile?: CueFile1;
	assignable: boolean;
}[];
